# Use an official Python runtime as a parent image
FROM python:3.9

# Install Redis
RUN apt-get update && apt-get install -y redis-server

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY app app/
COPY migrations migrations/
COPY blog_posts blog_posts/
COPY requirements.txt .
COPY config.py .

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Make port $PORT available to the world outside this container
EXPOSE $PORT

# Start the Flask application; Add -- reload to hot reload in development
CMD gunicorn app:app --bind 0.0.0.0:$PORT --workers 4  --access-logfile - --error-logfile -