"""Added created_date and modified_date Nullable to Itinerary model.

Revision ID: 0c61bd60e0aa
Revises: 4ab8c6630156
Create Date: 2023-03-13 22:10:37.599853

"""
from datetime import datetime

import sqlalchemy as sa
from alembic import op

from app import db
from app.models import Itinerary

# revision identifiers, used by Alembic.
revision = "0c61bd60e0aa"
down_revision = "4ab8c6630156"
branch_labels = None
depends_on = None


# Define the new column
created_col = sa.Column("created_date", sa.DateTime(), nullable=True)
modified_col = sa.Column("modified_date", sa.DateTime(), nullable=True)


def upgrade():
    # Add the new column to the User table
    with op.batch_alter_table("itinerary", schema=None) as batch_op:
        batch_op.add_column(created_col)
        batch_op.add_column(modified_col)

    # Update the new column with the current timestamp
    connection = op.get_bind()
    connection.execute(
        sa.text(
            "UPDATE itinerary SET created_date = :timestamp, modified_date = :timestamp WHERE created_date IS NULL AND modified_date IS NULL"
        ),
        {"timestamp": datetime.utcnow()},
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("itinerary", schema=None) as batch_op:
        batch_op.drop_column("modified_date")
        batch_op.drop_column("created_date")

    # ### end Alembic commands ###
