"""Initial migration.

Revision ID: 4ab8c6630156
Revises: 
Create Date: 2023-03-12 07:07:24.929507

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4ab8c6630156"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "itinerary",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("destination", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("interests", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("markdown", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("itinerary")
    # ### end Alembic commands ###
