"""Added is_budget_friendly flag to Itinerary table.

Revision ID: 6df32a6991f7
Revises: 59076901e9bc
Create Date: 2023-03-21 15:16:56.856424

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6df32a6991f7"
down_revision = "59076901e9bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("itinerary", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_budget_friendly", sa.BOOLEAN(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("itinerary", schema=None) as batch_op:
        batch_op.drop_column("is_budget_friendly")

    # ### end Alembic commands ###
