name: Deploy to Heroku

on:
  push:
    branches:
      - main # Replace 'main' with the name of your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Heroku CLI
      uses: heroku/actions/setup@v1.1.3
      with:
        api_key: ${{ secrets.HEROKU_API_KEY }}

    - name: Build and push Docker images
      env:
        HEROKU_APP_NAME: vacabot # Replace with your Heroku app's name
      run: |
        heroku container:push web --app $HEROKU_APP_NAME
        heroku container:push worker --app $HEROKU_APP_NAME
        heroku container:release web worker --app $HEROKU_APP_NAME

    - name: Run database migrations
      env:
        HEROKU_APP_NAME: vacabot # Replace with your Heroku app's name
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku run flask db upgrade --app $HEROKU_APP_NAME
