name: Deploy to Heroku

on:
  push:
    branches:
      - main # Replace 'main' with the name of your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Heroku Container Registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login

    - name: Build and push Docker image
      env:
        HEROKU_APP_NAME: vacabot # Replace with your Heroku app's name
      run: |
        heroku container:push web --app $HEROKU_APP_NAME
        heroku container:release web --app $HEROKU_APP_NAME
