name: Deploy to Heroku

on:
  push:
    branches:
      - main # Replace 'main' with the name of your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    
    - name: "Deploy the web dyno"
      uses: "akhileshns/heroku-deploy@v3.12.12"
      with:
        docker_heroku_process_type: web
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: vacabot
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        justlogin: true
      
    - name: Login to Heroku Container Registry
      run: heroku container:login

    - name: Build and push Docker images
      env:
        HEROKU_APP_NAME: vacabot # Replace with your Heroku app's name
      run: |
        heroku container:push web worker --recursive --app $HEROKU_APP_NAME
        heroku container:release web worker --app $HEROKU_APP_NAME
    - name: Run database migrations
      env:
        HEROKU_APP_NAME: vacabot # Replace with your Heroku app's name
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku run flask db upgrade --app $HEROKU_APP_NAME
